/*
Copyright 2021 Murugappan Sevugan Chetty
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GqlSourceListerExpansion allows custom methods to be added to
// GqlSourceLister.
type GqlSourceListerExpansion interface{}

// GqlSourceNamespaceListerExpansion allows custom methods to be added to
// GqlSourceNamespaceLister.
type GqlSourceNamespaceListerExpansion interface{}
