// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "knative.dev/pkg/apis/duck/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GqlSource) DeepCopyInto(out *GqlSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GqlSource.
func (in *GqlSource) DeepCopy() *GqlSource {
	if in == nil {
		return nil
	}
	out := new(GqlSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GqlSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GqlSourceList) DeepCopyInto(out *GqlSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GqlSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GqlSourceList.
func (in *GqlSourceList) DeepCopy() *GqlSourceList {
	if in == nil {
		return nil
	}
	out := new(GqlSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GqlSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GqlSourceSpec) DeepCopyInto(out *GqlSourceSpec) {
	*out = *in
	if in.SubscriptionQueries != nil {
		in, out := &in.SubscriptionQueries, &out.SubscriptionQueries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sink != nil {
		in, out := &in.Sink, &out.Sink
		*out = new(v1.Destination)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GqlSourceSpec.
func (in *GqlSourceSpec) DeepCopy() *GqlSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GqlSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GqlSourceStatus) DeepCopyInto(out *GqlSourceStatus) {
	*out = *in
	in.SourceStatus.DeepCopyInto(&out.SourceStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GqlSourceStatus.
func (in *GqlSourceStatus) DeepCopy() *GqlSourceStatus {
	if in == nil {
		return nil
	}
	out := new(GqlSourceStatus)
	in.DeepCopyInto(out)
	return out
}
