/*
Copyright 2021 Murugappan Sevugan Chetty
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/itsmurugappan/gql-source/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGqlSources implements GqlSourceInterface
type FakeGqlSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var gqlsourcesResource = schema.GroupVersionResource{Group: "sources.muru.dev", Version: "v1alpha1", Resource: "gqlsources"}

var gqlsourcesKind = schema.GroupVersionKind{Group: "sources.muru.dev", Version: "v1alpha1", Kind: "GqlSource"}

// Get takes name of the gqlSource, and returns the corresponding gqlSource object, and an error if there is any.
func (c *FakeGqlSources) Get(name string, options v1.GetOptions) (result *v1alpha1.GqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gqlsourcesResource, c.ns, name), &v1alpha1.GqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GqlSource), err
}

// List takes label and field selectors, and returns the list of GqlSources that match those selectors.
func (c *FakeGqlSources) List(opts v1.ListOptions) (result *v1alpha1.GqlSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gqlsourcesResource, gqlsourcesKind, c.ns, opts), &v1alpha1.GqlSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GqlSourceList{ListMeta: obj.(*v1alpha1.GqlSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.GqlSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gqlSources.
func (c *FakeGqlSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gqlsourcesResource, c.ns, opts))

}

// Create takes the representation of a gqlSource and creates it.  Returns the server's representation of the gqlSource, and an error, if there is any.
func (c *FakeGqlSources) Create(gqlSource *v1alpha1.GqlSource) (result *v1alpha1.GqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gqlsourcesResource, c.ns, gqlSource), &v1alpha1.GqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GqlSource), err
}

// Update takes the representation of a gqlSource and updates it. Returns the server's representation of the gqlSource, and an error, if there is any.
func (c *FakeGqlSources) Update(gqlSource *v1alpha1.GqlSource) (result *v1alpha1.GqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gqlsourcesResource, c.ns, gqlSource), &v1alpha1.GqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GqlSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGqlSources) UpdateStatus(gqlSource *v1alpha1.GqlSource) (*v1alpha1.GqlSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gqlsourcesResource, "status", c.ns, gqlSource), &v1alpha1.GqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GqlSource), err
}

// Delete takes name of the gqlSource and deletes it. Returns an error if one occurs.
func (c *FakeGqlSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gqlsourcesResource, c.ns, name), &v1alpha1.GqlSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGqlSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gqlsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GqlSourceList{})
	return err
}

// Patch applies the patch and returns the patched gqlSource.
func (c *FakeGqlSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gqlsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GqlSource), err
}
