// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/itsmurugappan/gql-source/pkg/apis/sources/v1alpha1"
	scheme "github.com/itsmurugappan/gql-source/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GqlSourcesGetter has a method to return a GqlSourceInterface.
// A group's client should implement this interface.
type GqlSourcesGetter interface {
	GqlSources(namespace string) GqlSourceInterface
}

// GqlSourceInterface has methods to work with GqlSource resources.
type GqlSourceInterface interface {
	Create(*v1alpha1.GqlSource) (*v1alpha1.GqlSource, error)
	Update(*v1alpha1.GqlSource) (*v1alpha1.GqlSource, error)
	UpdateStatus(*v1alpha1.GqlSource) (*v1alpha1.GqlSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GqlSource, error)
	List(opts v1.ListOptions) (*v1alpha1.GqlSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GqlSource, err error)
	GqlSourceExpansion
}

// gqlSources implements GqlSourceInterface
type gqlSources struct {
	client rest.Interface
	ns     string
}

// newGqlSources returns a GqlSources
func newGqlSources(c *SourcesV1alpha1Client, namespace string) *gqlSources {
	return &gqlSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gqlSource, and returns the corresponding gqlSource object, and an error if there is any.
func (c *gqlSources) Get(name string, options v1.GetOptions) (result *v1alpha1.GqlSource, err error) {
	result = &v1alpha1.GqlSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gqlsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GqlSources that match those selectors.
func (c *gqlSources) List(opts v1.ListOptions) (result *v1alpha1.GqlSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GqlSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gqlsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gqlSources.
func (c *gqlSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gqlsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gqlSource and creates it.  Returns the server's representation of the gqlSource, and an error, if there is any.
func (c *gqlSources) Create(gqlSource *v1alpha1.GqlSource) (result *v1alpha1.GqlSource, err error) {
	result = &v1alpha1.GqlSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gqlsources").
		Body(gqlSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gqlSource and updates it. Returns the server's representation of the gqlSource, and an error, if there is any.
func (c *gqlSources) Update(gqlSource *v1alpha1.GqlSource) (result *v1alpha1.GqlSource, err error) {
	result = &v1alpha1.GqlSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gqlsources").
		Name(gqlSource.Name).
		Body(gqlSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *gqlSources) UpdateStatus(gqlSource *v1alpha1.GqlSource) (result *v1alpha1.GqlSource, err error) {
	result = &v1alpha1.GqlSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gqlsources").
		Name(gqlSource.Name).
		SubResource("status").
		Body(gqlSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the gqlSource and deletes it. Returns an error if one occurs.
func (c *gqlSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gqlsources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gqlSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gqlsources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gqlSource.
func (c *gqlSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GqlSource, err error) {
	result = &v1alpha1.GqlSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gqlsources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
