apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: restaurant
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: ko://github.com/itsmurugappan/gql-source/examples/restaurant-app/cmd/restaurant
