apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gql-sources-controller-admin
  labels:
    sources.muru.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: gql-source-controller
    namespace: knative-sources
roleRef:
  kind: ClusterRole
  name: gql-sources-admin
  apiGroup: rbac.authorization.k8s.io
