apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    sources.muru.dev/release: devel
    eventing.knative.dev/source: "true"
    duck.knative.dev/source: "true"
    muru.dev/crd-install: "true"
  annotations:
    registry.knative.dev/eventTypes: |
      [
        { "type": "dev.knative.gql.event" }
      ]
  name: gqlsources.sources.muru.dev
spec:
  group: sources.muru.dev
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: GqlSource
    plural: gqlsources
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: GqlServer
      type: string
      JSONPath: ".spec.gqlServer"
    - name: Sink
      type: string
      JSONPath: ".spec.sink.ref.name"
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  versions:
  - name: v1alpha1
    served: true
    storage: true