// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	sourcesv1alpha1 "github.com/itsmurugappan/gql-source/pkg/apis/sources/v1alpha1"
	versioned "github.com/itsmurugappan/gql-source/pkg/client/clientset/versioned"
	internalinterfaces "github.com/itsmurugappan/gql-source/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/itsmurugappan/gql-source/pkg/client/listers/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GqlSourceInformer provides access to a shared informer and lister for
// GqlSources.
type GqlSourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GqlSourceLister
}

type gqlSourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGqlSourceInformer constructs a new informer for GqlSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGqlSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGqlSourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGqlSourceInformer constructs a new informer for GqlSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGqlSourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SourcesV1alpha1().GqlSources(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SourcesV1alpha1().GqlSources(namespace).Watch(options)
			},
		},
		&sourcesv1alpha1.GqlSource{},
		resyncPeriod,
		indexers,
	)
}

func (f *gqlSourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGqlSourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gqlSourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sourcesv1alpha1.GqlSource{}, f.defaultInformer)
}

func (f *gqlSourceInformer) Lister() v1alpha1.GqlSourceLister {
	return v1alpha1.NewGqlSourceLister(f.Informer().GetIndexer())
}
