// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"

	fake "github.com/itsmurugappan/gql-source/pkg/client/injection/informers/factory/fake"
	gqlsource "github.com/itsmurugappan/gql-source/pkg/client/injection/informers/sources/v1alpha1/gqlsource"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = gqlsource.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Sources().V1alpha1().GqlSources()
	return context.WithValue(ctx, gqlsource.Key{}, inf), inf.Informer()
}
