# name: Build

# on:
#   push:
#     branches: [ 'master', 'release-*' ]
#   pull_request:
#     branches: [ 'master', 'release-*' ]

# jobs:

#   build:
#     name: Build
#     strategy:
#       matrix:
#         go-version: [1.15.x]
#         platform: [ubuntu-latest]

#     runs-on: ${{ matrix.platform }}

#     steps:

#       - name: Set up Go ${{ matrix.go-version }}
#         uses: actions/setup-go@v2
#         with:
#           go-version: ${{ matrix.go-version }}
#         id: go

#       - name: Check out code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 1

#       - name: Vet
#         run: go vet ./...

#       - name: Build
#         run: go build -v ./...
